### ISSUE TITLE
How to solve the estimation problem for people with different body sizes?

### ISSUE THREAD

**Issue by SlimeVRX** [facebookresearch/AGRoL#1]
Hi,

Input: Position and orientation information of the head and both hands

The model is trained with the size of the SMPL model with fixed arm length.

In reality, each person has a different body size.

How to solve the estimation problem for people with different body sizes?

Thank you!

**Comment by dulucas** [comment]
Hi, thanks for your interests in our work!

Great question, indeed, in this paper we use a unified human model. In practice, one solution might be normalizing the input data and scale it to the size of the human model.

**Comment by SlimeVRX** [comment]
Hi, Thank you for your reply!
