### ISSUE TITLE
Acceleration

### ISSUE THREAD

**Issue by yufu-liu** [facebookresearch/AGRoL#10]
Hi, I have dealt with this project for a month, and my recent goal is to have a real-time demo.

However, In real-time situation, my plotting time of each frame is around 0.05 seconds which is still not as fast as 0.0167 seconds (60Hz).

Do you have any suggestion for accelerate the preprocessing part, inference part, or visualization tool?

**Comment by asanakoy** [comment]
Sorry, but the visualization speedup was not part of the project.
