### ISSUE TITLE
How to prepare dataset for AGRoL

### ISSUE THREAD

**Issue by DarthRaol** [facebookresearch/AGRoL#4]
Hi,
I'm currently facing an issue with preparing dataset for training and testing. 

I have added SMPLH model file and allotted it as support_dir . but I'm getting a bug which says  **'posedirs is not a file in the archive'**

Also, We were unable to find **BioMotionLab_NTroje** and **MPI_HDM05** on AMASS webpage. Could you let us know how to download them.

We are also adding the error below : 

 _C:\Users\Admin>python E:\AGRoLmain\prepare_data.py --support_dir E:\AGRoLmain\ --save_dir ./dataset/AMASS/ --root_dir E:\AGRoLmain\dataset\AMASS
Traceback (most recent call last):
  File "E:\AGRoLmain\prepare_data.py", line 194, in <module>
    bm_male = BodyModel(
  File "E:\AGRoLmain\human_body_prior\body_model\body_model.py", line 68, in __init__
    npose_params = smpl_dict['posedirs'].shape[2] // 3
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\npyio.py", line 251, in __getitem__
    raise KeyError("%s is not a file in the archive" % key)
KeyError: 'posedirs is not a file in the archive'_

Thank you !

**Comment by dulucas** [comment]
Hi, thanks for your interests in our work!

It might because you didn't enter correctly your "support_dir"? The support_dir should indicate the dir that contains both your "smplh" and "dmpls".

The **BioMotionLab_NTroje** refers to **BMLrub**.
The **MPI_HDM05** refers to **HDM05**.

Hope it helps.

**Comment by whl-007** [comment]
Could you tell me what is "dmpls"?Should both "train/" and "test/" have a certain proportion of data, such as dividing the BioMotionLab_NTroje dataset into a 70:30 ratio and placing them respectively?
