### ISSUE TITLE
Running the model on real data

### ISSUE THREAD

**Issue by jsaisagar** [facebookresearch/AGRoL#5]
Hi,

Thanks for the amazing work and releasing the models.

I have a query regarding running the model with real data captured from HMD devices. The network has been trained on AMASS data whose coordinate system is different from that of real-world data. Does the model work in these scenarios? Or is there any preprocessing we can do for real data to work on models trained with AMASS data?

Thanks for any help,
Sai

**Comment by asanakoy** [comment]
Hi Sai, very good question!
When we were running tests on real data from Quest, we had to convert the coordinate system from the trackers' to the SMPL ones. And it is indeed pretty cumbersome to do. Unfortunately we cannot share the conversion code right now.

**Comment by Combo1** [comment]
Awesome project! Could you elaborate on the conversion of coordinate system from the tracker to SMPL without code? It is quite hard to find any information about this issue online.
