### ISSUE TITLE
MLP model weights

### ISSUE THREAD

**Issue by StefanoBraghetto** [facebookresearch/AGRoL#7]
Hello,

I'm encountering an error while attempting to load the weights of the MLP model. I'm unsure if I'm misunderstanding something, but it seems that the weights provided in the following link: https://github.com/facebookresearch/AGRoL/releases/download/v0/agrol_AMASS_pretrained_weights.zip (specifically in the diffmlp.pt file) are meant for the diffusion model. As the MLP model has a different state_dict shape upon creation, I believe these weights won't work for it.

if I'm not wrong, Are there any plans to share the weights specifically for the MLP model as well?

Thank you for your response and help!

**Comment by asanakoy** [comment]
Hi there. Unfortunately we don't have the MLP weights to share right now. But you can easily retrain the network in less than one day on a single GPU.
