### ISSUE TITLE
Coordinate system and scale

### ISSUE THREAD

**Issue by yufu-liu** [facebookresearch/AGRoL#9]
Hi! Thanks for this amazing work!
I am adapting this algorithm to my VR devices so that I can play with it.
However, I encounter an issue that the data from my devices are not similar to the one from dataset. I guess it's because of coordintate system or the scale. 

Does the dataset use right-hand coordinate system and meter in scale?
(The data shows that controllers' position are silmilar in z-axis rather than y-axis.)

**Comment by yufu-liu** [comment]
After checking the transformation functions step by step, I found the axes change during transfrom from local  to global.

**Comment by Combo1** [comment]
Hi ^^ Could you share what kind of transformations you needed to apply to transform your VR device coordinates into the coordinate system used by AGRoL?
